### ISSUE TITLE
Feature: use -- to get subcommand set

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-args#1]
There are scenarios when you need to pass a set of command for an argument. I think common way to do it is to use -- separator.
Example.

```bash
docker.js run -it  ubuntu  sh -c "echo 123"
```

So here I want to pass [sh -c "echo 123"] to "ubuntu" argument. 
Pixl-Args would consider -c  as an argument for the main script. Would be nice to have "--" feature to specify where those sub commands should go. E.g.
```bash
docker.js run -it  ubuntu  -- sh -c "echo 123"
```
And in this case args.other would be ["ubuntu", "sh", "-c", "echo 123"]. CUrrently it would resolve to ["ubuntu", "sh"], and c would go as separate arg.

**Comment by jhuckaby** [comment]
Doesn't this syntax provide the desired effect?

```sh
docker.js run -it --ubuntu 'sh -c "echo 123"'
```

Produces:

```json
{
	"other": [
		"run"
	],
	"it": true,
	"ubuntu": "sh -c \"echo 123\""
}
```

**Comment by mikeTWC1984** [comment]
Let me give you a better example. Say I want a cli tool to spawn child process. 
```js

  const child = cp.spawn('ubuntu', ["sh", "-c", "echo 123"])

```

So what I want is to grab command ("ubuntu") and argument array from the cli tool.

"ubuntu" also should not be named argument. It should come from  args.other[1]  (so I can use "centos" or "redhat")

I believe "--" is just common way of approaching this issue

**Comment by jhuckaby** [comment]
Apologies for my misunderstanding.  I've never heard of the `--` convention before, so this is all new to me.  Let me do some research to see how it should behave.

**Comment by jhuckaby** [comment]
Okay, so:

> In Linux command-line syntax, the double-dash (--) is used to signify the end of command options. After the double-dash, no more command line options will be interpreted as flags or options to the command itself. Instead, they will be treated as positional arguments or passed as-is to the command being run.

So if I encounter that `--` thing by itself, it should stop processing command-line arguments, and treat the rest of the command-line as a single sole argument?

That's fine, but how should it returned to the calling code?  What I mean is, `pixl-args` generates a simple object of key/value pairs.  What key/name should I use for this new thing?

Right now, when `pixl-args` finds an argument that doesn't match the `--NAME` pattern, it appends it to an `other` array.  Should I just do that with the `--` argument too?

For example, should this command:

```sh
docker.js run -it ubuntu -- sh -c "echo 123"
```

Produce this when you call `args.get()`?

```json
{
	"other": [
		"run",
		"sh -c \"echo 123\"",
	],
	"it": "ubuntu"
}
```

There is another, separate issue here.  `pixl-args` doesn't process single-dash (-) in the way you expect either.  It only does key/value pairs, and nothing else, hence `--it ubuntu` becomes:

```json
{
	"it": "ubuntu"
}
```

It assumes `it` is the key, and `ubuntu` is that value of that key.

I assume you're expecting something more like:

```json
{
	"i": true,
	"t": true,
	"other": [
		"run",
		"ubuntu",
		"sh -c \"echo 123\"",
	],
}
```

But it just isn't designed to process command-line args in this way.

Maybe you're looking for something like [meow](https://github.com/sindresorhus/meow)?

**Comment by mikeTWC1984** [comment]
So basically, I'd expect anything after -- go to "other" array.  Like "other" :  ["run", "sh", "-c", "echo 123" ]
As I understand "--" indicates that all following arguments are positional (not named).

I'll take a look at meow

**Comment by jhuckaby** [comment]
Okay, I just published `pixl-args` v1.0.5, which now handles this:

```sh
node docker.js run -it ubuntu -- sh -c "echo 123"
```

And produces this from `args.get()`:

```json
{
	"other": [
		"run",
		"ubuntu",
		"sh",
		"-c",
		"echo 123"
	],
	"i": true,
	"t": true
}
```

Note that I am also detecting single-dash args (e.g. `-it`) and parsing them as individual single-character flags, `i` and `t`.

New document sections added:

## Single Dash Args

Arguments with a single dash are considered to be flags, and are parsed differently.  Each character is considered to be its own separate key, and they cannot be set to a specific value (they are always `true`).  For example:

```sh
node your-script.js -abc
```

Then calling `get()`, this becomes:

```json
{
	"a": true,
	"b": true,
	"c": true
}
```

Note that `-abc`, `-a -b -c` and even `--a --b --c` all produce the same result.

## Double-Dash Separator

If a double-dash separator (`--`) is encountered, then named argument processing stops, and anything after the `--` is added onto the `other` array.  Example:

```sh
node your-script.js --key1 value1 --key2 value2 -- --key3 value3 --key4 value4
```

Then calling `get()`, this becomes:

```json
{
	"key1": "value1",
	"key2": "value2",
	"other": [
		"--key3",
		"value3",
		"--key4",
		"value4"
	]
}
```

**Comment by mikeTWC1984** [comment]
Nice, TY

However I see another issue now: single dash args now treated as boolean / flag. eg. 
```script.js -e 123```
will resolve into e: true, other: 123
and no e: 123

**Comment by jhuckaby** [comment]
Well therein lies an ambiguity issue.  I am struggling to understand when to parse this as a single key/value pair named `it` having value `ubuntu`:

```sh
-it ubuntu
```

e.g.

```json
{
	"it": "ubuntu"
}
```

And when to parse it as flags, e.g. `i`, `t`, and then `ubuntu` separately as an other, like this:

```json
{
	"i": true,
	"t": true,
	"other": [
		"ubuntu"
	]
}
```

I thought `i` and `t` were separate flags that represented feature toggles.  Is this not the case?

I figured that I could use the number of dashes as the "trigger" on parsing behavior.  Single dash means flag.  Double-dash means key/value pair.

Did I misunderstand the use case?

**Comment by mikeTWC1984** [comment]
Mm. I just use -it as common docker example. Typically in cli's   "-xyz file"  is the same as -x -y -z file. For my use case I'm good with previous version (like having -it x as it:x)

**Comment by mikeTWC1984** [comment]
> Well therein lies an ambiguity issue. I am struggling to understand when to parse this as a single key/value pair named `it` having value `ubuntu`:
> 
> ```shell
> -it ubuntu
> ```
> 
> e.g.
> 
> ```json
> {
> 	"it": "ubuntu"
> }
> ```
> 
> And when to parse it as flags, e.g. `i`, `t`, and then `ubuntu` separately as an other, like this:
> 
> ```json
> {
> 	"i": true,
> 	"t": true,
> 	"other": [
> 		"ubuntu"
> 	]
> }
> ```
> 
> I thought `i` and `t` were separate flags that represented feature toggles. Is this not the case?
> 
> I figured that I could use the number of dashes as the "trigger" on parsing behavior. Single dash means flag. Double-dash means key/value pair.
> 
> Did I misunderstand the use case?

I think single dash is just short version of double dash. E.g. --network vs -n

**Comment by jhuckaby** [comment]
I am having trouble understanding the desired behavior.  I'll just remove the single dash code and treat any number of dashes the same.

**Comment by jhuckaby** [comment]
v1.0.6 published.  This:

```sh
node argtest.js run -it ubuntu -- sh -c "echo 123"
```

Now parses as:

```json
{
	"other": [
		"run",
		"sh",
		"-c",
		"echo 123"
	],
	"it": "ubuntu"
}
```

**Comment by mikeTWC1984** [comment]
OK, perfect. I'm totally fine. The feature you were trying to add (combining args) is also very common, e.g.
```tar -xvf archive.tar```
But it's more like convenience, there is no issue to type -x -v -f.

**Comment by jhuckaby** [comment]
Yup, tar's args are a great example of what I was *trying* to emulate.  But there are nuances and ambiguities that confounded me 😝 

Glad we got it working for you 👍🏻 

Thanks!
